### ISSUE TITLE
Example broken?

### ISSUE THREAD

**Issue by MTRNord** [slack-rs/slack-rs#73]
Example crashes with:` Error: Slack Api Error: "Invalid scheme for Http"`

Full backtrace (don't mind that it says `TG_sync-rs` It is implemented in my program[1]):

```
thread 'main' panicked at 'Error: Slack Api Error: "Invalid scheme for Http"', src/main.rs:59
stack backtrace:
   0:     0x55957503edb3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h3c67687ba454b78b
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55957503aa74 - std::sys_common::backtrace::_print::h701c2403afe49d2d
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x559575041acc - std::panicking::default_hook::{{closure}}::h07b8ee04b5734d1a
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x559575041694 - std::panicking::default_hook::h23eeafbf7c1c05c3
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x559575041f1b - std::panicking::rust_panic_with_hook::hd0067971b6d1240e
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x559575041da4 - std::panicking::begin_panic::h1fd1f10a3de8f902
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x559575041d29 - std::panicking::begin_panic_fmt::haa043917b5d6f21b
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x559574b76f07 - tg_sync::slack::hd0e46d2bc3e8cd8f
                               at /daten/Documents/TG_sync-rs/src/main.rs:59
   8:     0x559574b76c2c - tg_sync::main::haa61563c31f19035
                               at /daten/Documents/TG_sync-rs/src/main.rs:42
   9:     0x559575041c15 - std::panicking::try::do_call::hecedd59d47f867be
                               at /checkout/src/libstd/panicking.rs:454
  10:     0x559575048f7a - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  11:     0x5595750426c6 - std::rt::lang_start::hb7fc7ec87b663023
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:57
  12:     0x559574b77d52 - main
  13:     0x7fd6f5818510 - __libc_start_main
  14:     0x559574879ae9 - _start
  15:                0x0 - <unknown>
```

You will notice if you take a look at my code linked below I updated Hyper and openssl. as well as the Websocket crate. But as there are no API changes it normally should run fine.

My specs are (if needed):
Linux antergos 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux (Arch Linux)
OpenSSL 1.0.2k  26 Jan 2017

[1] https://github.com/Nordgedanken/TG_sync-rs/

**Comment by compressed** [comment]
@MTRNord check #70 for what's required for updating openssl.

**Comment by blakehawkins** [comment]
Well, it doesn't really say.

* check out @compressed 's fork in branch `tungstenite`
* Add this to your `Cargo.toml`  file:

```
[replace]
"slack:0.16.0" = { path = "../slack-rs-tungstenite" }
```

Example still won't work - you'll have to update the `on_ping` and `post_message` calls - or just remove them.

**Comment by BenTheElder** [comment]
This should be fixed.
