### ISSUE TITLE
Bot is disconnected but doese't notice

### ISSUE THREAD

**Issue by dten** [slack-rs/slack-rs#86]
Hey I had this several weeks ago and haven't had it since until now.
Basically the bot appears offline but it's actually waiting on the websocket

in preparation i've been building release with debug sources and i have this stack trace. sadly i can't really see which websocket command it's waiting on because it's still release (it does say read though)

We used to have a timeout set on the underlying socket to work around the other websocket library

```
(gdb) bt
#0  0x00007fa984221102 in recv () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fa9855ad42f in _$LT$std..net..tcp..TcpStream$u20$as$u20$std..io..Read$GT$::read::h08a6bc50c3293175 ()
    at /checkout/src/libstd/sys/unix/net.rs:161
#2  0x00007fa9854e3053 in std::panicking::try::do_call::h569c007b8386635e ()
#3  0x00007fa9855bd2cb in __rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:98
#4  0x00007fa9854e3ad6 in openssl::ssl::bio::bread::h20a49d7450378b36 ()
#5  0x00007fa98491c139 in BIO_read () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#6  0x00007fa984c391e1 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#7  0x00007fa984c3a41d in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#8  0x00007fa984c375e0 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#9  0x00007fa985139667 in tungstenite::input_buffer::InputBuffer::read_from::h95abdbaba330b42c ()
#10 0x00007fa98515dc73 in slack::RtmClient::run::hcef610b3e818eb3e ()
#11 0x00007fa9852042d5 in sirbotalot::main::hfa1e56b4aa13694e ()
#12 0x00007fa9855b5fe6 in std::panicking::try::do_call::h689a21caeeef92aa () at /checkout/src/libstd/panicking.rs:454
#13 0x00007fa9855bd2cb in __rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:98
#14 0x00007fa9855b6a97 in std::rt::lang_start::hf63d494cb7dd034c () at /checkout/src/libstd/panicking.rs:433
#15 0x00007fa983c5c7ed in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#16 0x00007fa985134f1d in _start ()
```

**Comment by dten** [comment]
think we need the timeout again
https://github.com/snapview/tungstenite-rs/issues/15#issuecomment-308418092

**Comment by BenTheElder** [comment]
Closed via https://github.com/slack-rs/slack-rs/pull/87
